name: simple_progress_dialog
description: A simple full-screen progress dialog for Flutter.
version: 0.1.0
homepage: https://twitter.com/K9i_apps
repository: https://github.com/K9i-0/simple_progress_dialog

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
