name: simple_loading_dialog
description: "SimpleLoadingDialog: A seamless full-screen loading dialog for Flutter. Efficiently manage actions while awaiting Futures, and easily customize with Widgets and ThemeExtension."
version: 0.6.0
homepage: https://twitter.com/K9i_apps
repository: https://github.com/K9i-0/simple_loading_dialog

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  yumemi_lints: ^2.1.0

flutter:
